import { pgTable, text, real, integer } from "drizzle-orm/pg-core";

export const strategiesTable = pgTable("strategies", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  type: text("type"),
  pair: text("pair").default("R_75"),
  status: text("status").default("active"),
  entryTimeframe: text("entry_timeframe").default("1m"),
  signalTimeframe: text("signal_timeframe").default("5m"),
  trendTimeframe: text("trend_timeframe").default("15m"),
  sessionsEnabled: text("sessions_enabled").default("[]"),
  scoreThreshold: integer("score_threshold").default(38),
  maxTradesDay: integer("max_trades_day").default(6),
  maxTradesHour: integer("max_trades_hour").default(3),
  consecutiveLossStop: integer("consecutive_loss_stop").default(3),
  maxRiskPercent: real("max_risk_percent").default(1.0),
  stopMultiplier: real("stop_multiplier").default(1.5),
  tp1Multiplier: real("tp1_multiplier").default(1.5),
  tp2Multiplier: real("tp2_multiplier").default(3.0),
  counterTrendEnabled: integer("counter_trend_enabled").default(0),
  counterTrendRsiThreshold: real("counter_trend_rsi_threshold").default(78),
  counterTrendBbSigma: real("counter_trend_bb_sigma").default(2.5),
  consolidationDetection: integer("consolidation_detection").default(1),
  firstCandleRule: integer("first_candle_rule").default(1),
  spikeFilterEnabled: integer("spike_filter_enabled").default(1),
  spikeFilterMultiplier: real("spike_filter_multiplier").default(3.0),
  momentumExtensionEnabled: integer("momentum_extension_enabled").default(1),
  weightTrend: real("weight_trend").default(1.0),
  weightVolatility: real("weight_volatility").default(1.0),
  weightTiming: real("weight_timing").default(1.0),
  weightPullback: real("weight_pullback").default(1.0),
  weightRisk: real("weight_risk").default(1.0),
  autoPauseOnLosses: integer("auto_pause_on_losses").default(5),
  circuitBreakerActive: integer("circuit_breaker_active").default(0),
  circuitBreakerTriggeredAt: integer("circuit_breaker_triggered_at"),
  createdAt: integer("created_at"),
  updatedAt: integer("updated_at"),
  createdBy: text("created_by"),
  usersAssigned: integer("users_assigned").default(0),
  totalTrades: integer("total_trades").default(0),
  winRate: real("win_rate").default(0),
  avgScore: real("avg_score").default(0),
});

export type Strategy = typeof strategiesTable.$inferSelect;

export const strategyPerformanceTable = pgTable("strategy_performance", {
  id: text("id").primaryKey(),
  strategyId: text("strategy_id"),
  userId: text("user_id"),
  date: integer("date"),
  tradesCount: integer("trades_count"),
  wins: integer("wins"),
  losses: integer("losses"),
  pnl: real("pnl"),
  avgScore: real("avg_score"),
  bestSession: text("best_session"),
  indicatorRsiAccuracy: real("indicator_rsi_accuracy"),
  indicatorStochAccuracy: real("indicator_stoch_accuracy"),
  indicatorMacdAccuracy: real("indicator_macd_accuracy"),
  indicatorPullbackAccuracy: real("indicator_pullback_accuracy"),
  indicatorSmcAccuracy: real("indicator_smc_accuracy"),
});
